### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by qexat** [MININT2/minint.dev#1]
# Todo list

## Optimize Minty generation

- [ ] Load preferably generation data from external jsons

- [ ] Do some favicon cutesy stuff with the Mintys

## Create navbar and footer

- [ ] Partially transparent
- [ ] Stick to top
- [ ] Attempt SVG usage + animation

## Link to existing server services

- [ ] Seamlessly integrate into the Minint ecosystem

## Work on global chat dapp
